import { randomBytes } from 'node:crypto';

import { Room, type Client } from 'colyseus';

import {
  CELL_SIZE,
  COUNTDOWN_MS,
  END_SCREEN_MS,
  EXIT_COUNT,
  generateMaze,
  gridToWorldX,
  gridToWorldZ,
  isValidRoomCode,
  MAX_PLAYERS_PER_ROOM,
  MAZE_HEIGHT,
  MAZE_WIDTH,
  MIN_PLAYERS_PER_ROOM,
  MODE_CAPTURE,
  mulberry32,
  PHASE_COUNTDOWN,
  PHASE_ENDED,
  PHASE_LOBBY,
  PHASE_PLAYING,
  pickFloorCells,
  stepPlayer,
  TICK_INTERVAL_MS,
  type MazeGrid,
} from '@mazerush/shared';

import {
  applyGameTick,
  exitsToReadonly,
  pickExits,
  pickFlagCell,
} from '../game/GameRules.js';
import { MovementValidator } from '../game/MovementValidator.js';
import { ExitPoint } from '../schema/ExitPoint.js';
import { GameState } from '../schema/GameState.js';
import { PlayerState } from '../schema/PlayerState.js';
import { logger } from '../util/logger.js';
import { sanitizeName } from '../util/sanitize.js';

type RoomCreateOptions = {
  readonly code?: unknown;
};

type JoinOptions = {
  readonly name?: unknown;
};

export class MazeRoom extends Room<GameState> {
  override maxClients = MAX_PLAYERS_PER_ROOM;
  private maze: MazeGrid | null = null;
  private readonly validators = new Map<string, MovementValidator>();
  // Pre-picked spawn cells (deterministic via the maze seed). Popped on
  // join so each player gets a distinct starting cell. Late joiners after
  // pool exhaustion fall back to (1,1).
  private spawnCells: Array<readonly [number, number]> = [];

  override onCreate(options: RoomCreateOptions = {}): void {
    // Code is generated by the client (so it can show + share immediately
    // without an extra round-trip). Server still validates format and
    // publishes it as metadata, so the filterBy matchmaking gate has
    // something to match against.
    if (!isValidRoomCode(options.code)) {
      throw new Error('room creation requires a valid 6-char base32 code');
    }
    void this.setMetadata({ code: options.code });

    const seed = randomBytes(4).readUInt32BE(0);

    const state = new GameState();
    state.seed = seed;
    state.width = MAZE_WIDTH;
    state.height = MAZE_HEIGHT;
    state.mode = MODE_CAPTURE;
    state.phase = PHASE_LOBBY;
    this.setState(state);

    const maze = generateMaze({ width: MAZE_WIDTH, height: MAZE_HEIGHT, seed });
    this.maze = maze;

    // Spawn pool. Different seed-derived RNG than the exit shuffler so
    // spawns and exits don't correlate.
    const spawnRng = mulberry32(seed ^ 0xdeadbeef);
    this.spawnCells = pickFloorCells(maze, spawnRng, MAX_PLAYERS_PER_ROOM).map(
      (c) => [c[0], c[1]] as const,
    );

    // Flag at the maze center.
    const flagCell = pickFlagCell(maze);
    state.flag.x = gridToWorldX(flagCell.gx, maze.width, CELL_SIZE);
    state.flag.z = gridToWorldZ(flagCell.gy, maze.height, CELL_SIZE);
    state.flag.carriedBy = '';

    // Exits on the inner perimeter, never overlapping the flag.
    const exitCells = pickExits(maze, seed, EXIT_COUNT, [flagCell]);
    for (const cell of exitCells) {
      const e = new ExitPoint();
      e.gx = cell.gx;
      e.gy = cell.gy;
      state.exits.push(e);
    }

    this.setPatchRate(TICK_INTERVAL_MS);
    this.setSimulationInterval(() => this.tick(), TICK_INTERVAL_MS);
    this.onMessage('input', (client, raw: unknown) => this.handleInput(client, raw));

    logger.info(
      {
        roomId: this.roomId,
        code: options.code,
        seed,
        mode: state.mode,
        exits: exitCells.length,
      },
      'maze room created',
    );
  }

  override onJoin(client: Client, options: JoinOptions = {}): void {
    if (!this.maze) throw new Error('maze not initialized');

    const player = new PlayerState();
    player.id = client.sessionId;
    player.name = sanitizeName(options.name);

    const cell = this.spawnCells.shift() ?? [1, 1];
    player.x = gridToWorldX(cell[0], this.maze.width, CELL_SIZE);
    player.z = gridToWorldZ(cell[1], this.maze.height, CELL_SIZE);
    player.yaw = Math.PI;

    this.state.players.set(client.sessionId, player);
    this.validators.set(client.sessionId, new MovementValidator(Date.now()));

    logger.info(
      { roomId: this.roomId, sessionId: client.sessionId, name: player.name },
      'player joined',
    );
  }

  override onLeave(client: Client): void {
    const player = this.state.players.get(client.sessionId);

    // If the leaver was carrying the flag, drop it at their last known
    // position so the match stays winnable.
    if (player && this.state.flag.carriedBy === client.sessionId) {
      this.state.flag.carriedBy = '';
      this.state.flag.x = player.x;
      this.state.flag.z = player.z;
      logger.info(
        { roomId: this.roomId, sessionId: client.sessionId },
        'carrier left — flag dropped',
      );
    }

    this.state.players.delete(client.sessionId);
    this.validators.delete(client.sessionId);
    logger.info({ roomId: this.roomId, sessionId: client.sessionId }, 'player left');
  }

  override onDispose(): void {
    logger.info({ roomId: this.roomId }, 'maze room disposed');
  }

  // 20 Hz simulation tick. Two responsibilities:
  //   - drive the phase state machine (lobby → countdown → playing → ended)
  //   - while playing, run GameRules to detect pickups/wins
  private tick(): void {
    if (!this.maze) return;
    const now = Date.now();
    const state = this.state;

    switch (state.phase) {
      case PHASE_LOBBY:
        if (state.players.size >= MIN_PLAYERS_PER_ROOM) {
          state.phase = PHASE_COUNTDOWN;
          state.countdownEndsAt = now + COUNTDOWN_MS;
          logger.info(
            { roomId: this.roomId, players: state.players.size },
            'countdown started',
          );
        }
        return;
      case PHASE_COUNTDOWN:
        if (now >= state.countdownEndsAt) {
          state.phase = PHASE_PLAYING;
          state.countdownEndsAt = 0;
          logger.info({ roomId: this.roomId }, 'match started');
        }
        return;
      case PHASE_PLAYING:
        this.applyGamePlayingTick();
        return;
      case PHASE_ENDED:
        if (now >= state.endedAt + END_SCREEN_MS) {
          logger.info({ roomId: this.roomId }, 'end screen elapsed — disconnecting room');
          // Schedule disconnect on the next event-loop turn so the final
          // state patch broadcasts before we tear down.
          void this.disconnect();
        }
        return;
      default:
        return;
    }
  }

  private applyGamePlayingTick(): void {
    if (!this.maze) return;
    const playerIter: Array<{ sessionId: string; x: number; z: number }> = [];
    this.state.players.forEach((p, sid) => {
      playerIter.push({ sessionId: sid, x: p.x, z: p.z });
    });

    const events = applyGameTick({
      maze: this.maze,
      players: playerIter,
      flag: { x: this.state.flag.x, z: this.state.flag.z, carriedBy: this.state.flag.carriedBy },
      exits: exitsToReadonly(this.state.exits as unknown as ArrayLike<ExitPoint>),
      mode: this.state.mode,
    });

    for (const ev of events) {
      if (ev.kind === 'pickup') {
        this.state.flag.carriedBy = ev.sessionId;
        const carrier = this.state.players.get(ev.sessionId);
        if (carrier) {
          // Pin the flag's stored position to the carrier so a late-joining
          // client sees it in roughly the right place before the next tick.
          this.state.flag.x = carrier.x;
          this.state.flag.z = carrier.z;
        }
        logger.info(
          { roomId: this.roomId, sessionId: ev.sessionId },
          'flag picked up',
        );
      } else if (ev.kind === 'win') {
        this.state.phase = PHASE_ENDED;
        this.state.endedAt = Date.now();
        this.state.winnerId = ev.sessionId;
        logger.info(
          { roomId: this.roomId, sessionId: ev.sessionId },
          'match ended',
        );
      }
    }
  }

  private handleInput(client: Client, raw: unknown): void {
    if (!this.maze) return;
    const validator = this.validators.get(client.sessionId);
    const player = this.state.players.get(client.sessionId);
    if (!validator || !player) return;

    // Movement is only meaningful while the match is in progress (or in the
    // countdown, where you can still look around). Drop inputs outside that
    // window quietly — no rate-limit penalty, since it's the server's call.
    if (this.state.phase !== PHASE_PLAYING && this.state.phase !== PHASE_COUNTDOWN) {
      return;
    }

    const outcome = validator.process(raw, Date.now());
    switch (outcome.kind) {
      case 'apply': {
        const { input } = outcome;
        const next = stepPlayer(this.maze, { x: player.x, z: player.z }, input);
        player.x = next.x;
        player.z = next.z;
        player.yaw = input.yaw;
        player.lastSeq = input.seq;

        // If this player is carrying the flag, drag it along on every move.
        // (We only update flag pos when carriedBy is set; clients should
        // render the flag at the carrier's position regardless.)
        if (this.state.flag.carriedBy === client.sessionId) {
          this.state.flag.x = next.x;
          this.state.flag.z = next.z;
        }
        return;
      }
      case 'reject-speed': {
        player.yaw = outcome.yaw;
        player.lastSeq = outcome.seq;
        logger.warn(
          { sessionId: client.sessionId, seq: outcome.seq },
          'speed violation: rejecting move',
        );
        return;
      }
      case 'rate-limited':
        return;
      case 'drop-malformed':
        logger.debug({ sessionId: client.sessionId }, 'dropped malformed input');
        return;
      case 'kick':
        logger.warn(
          { sessionId: client.sessionId, code: outcome.code, reason: outcome.reason },
          'kicking player',
        );
        client.leave(outcome.code);
        return;
      default:
        outcome satisfies never;
    }
  }
}
